git clone --depth 1 https://github.com/FlowiseAI/Flowise
git clone --depth 1 https://github.com/trypromptly/LLMStack
git clone --depth 1 https://github.com/crewAIInc/crewAI
git clone --depth 1 https://github.com/n8n-io/n8n
git clone --depth 1 https://github.com/meta-llama/llama-models
git clone --depth 1 https://github.com/huggingface/smollm.git
git clone --depth 1 https://github.com/huggingface/pytorch-image-models
git clone --depth 1 https://github.com/openai/tiktoken
git clone --depth 1 https://github.com/huggingface/trl
git clone --depth 1 https://github.com/huggingface/diffusers
git clone --depth 1 https://github.com/huggingface/open-r1
git clone --depth 1 https://github.com/huggingface/candle
git clone --depth 1 https://github.com/huggingface/tokenizers
