git clone --depth 1 https://github.com/mdexSwap/contracts.git
git clone --depth 1 https://github.com/maverickprotocol/v2-interfaces.git
git clone --depth 1 https://github.com/PositionExchange/decentralized-perpetual-trading-protocol-core.git
git clone --depth 1 https://github.com/PositionExchange/decentralized-perpetual-trading-protocol-cross-chain.git
git clone --depth 1 https://github.com/PositionExchange/position-protocol.git
git clone --depth 1 https://github.com/bsx-exchange/contracts-core.git
git clone --depth 1 https://github.com/swaap-labs/swaap-earn-protocol.git
git clone --depth 1 https://gitlab.com/thorchain/thornode.git
git clone --depth 1 https://github.com/thorchain/docs.git
git clone --depth 1 https://github.com/drift-labs/protocol-v2.git
git clone --depth 1 https://github.com/IPOR-Labs/ipor-protocol.git
git clone --depth 1 https://github.com/gmx-io/gmx-interface.git
git clone --depth 1 https://github.com/gmx-io/gmx-contracts.git
git clone --depth 1 https://github.com/gmx-io/gmx-synthetics.git
git clone --depth 1 https://github.com/dydxprotocol/v4-web.git
git clone --depth 1 https://github.com/dydxprotocol/v4-chain.git
git clone --depth 1 https://github.com/dydxprotocol/v4-documentation.git
