git clone --depth 1 https://github.com/QuarryProtocol/quarry.git
git clone --depth 1 https://github.com/jup-ag/jupiter-amm-implementation.git
git clone --depth 1 https://github.com/orca-so/whirlpools.git
git clone --depth 1 https://github.com/AdrenaFoundation/adrena-abi.git
git clone --depth 1 https://github.com/Kamino-Finance/scope.git
git clone --depth 1 https://github.com/blockworks-foundation/autobahn.git
git clone --depth 1 https://github.com/blockworks-foundation/mango-v4.git 
git clone --depth 1 https://github.com/solana-labs/solana-program-library.git
git clone --depth 1 https://github.com/saber-hq/stable-swap.git
git clone --depth 1 https://github.com/project-serum/serum-dex.git
git clone --depth 1 https://github.com/solana-foundation/anchor.git
git clone --depth 1 https://github.com/solana-program/system.git
git clone --depth 1 https://github.com/solana-program/token.git
git clone --depth 1 https://github.com/solana-foundation/solana-com.git
git clone --depth 1 https://github.com/solana-foundation/specs.git
git clone --depth 1 https://github.com/solana-labs/solana.git
git clone --depth 1 https://github.com/raydium-io/raydium-ui-v3-public.git
git clone --depth 1 https://github.com/anza-xyz/agave.git
git clone --depth 1 https://github.com/raydium-io/raydium-clmm.git
git clone --depth 1 https://github.com/raydium-io/raydium-amm.git
